name: 'MailChimp Get Donors'
description: 'Retrieves donors from MailChimp contacts, groups by donor level and writes YAML files'

inputs:
  mailchimp_list_id:
    description: 'MailChimp list ID'
    required: true
  mailchimp_segment_id:
    description: 'MailChimp segment ID'
    required: true
  mailchimp_token:
    description: 'MailChimp API token'
    required: true
  mailchimp_server_prefix:
    description: 'MailChimp server prefix'
    required: true
  
runs:
  using: 'composite'
  steps:
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install poetry
      run: pip install poetry
      shell: bash

    - name: Install dependencies
      run: |
        if [ -f poetry.lock ]; then
          poetry install
        else
          poetry install --no-root
        fi
      shell: bash

    - name: Run MailChimp Action
      env:                                                                                                                                                                       
        MAILCHIMP_LIST_ID: ${{ inputs.mailchimp_list_id }}
        MAILCHIMP_SEGMENT_ID: ${{ inputs.mailchimp_segment_id }}
        MAILCHIMP_TOKEN: ${{ inputs.mailchimp_token }}
        MAILCHIMP_SERVER_PREFIX: ${{ inputs.mailchimp_server_prefix }}
      run: python main.py
      shell: bash